# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow,QDialog
from PyQt5 import QtCore, QtGui, QtWidgets
import ui
from ui import Ui_MainWindow
import main
import pandas as pd


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(760, 519)

        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(529, 146, 56, 17))
        self.checkBox.setObjectName("checkBox")

        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(530, 170, 28, 16))
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(564, 170, 60, 16))
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 140, 271, 111))
        self.layoutWidget.setObjectName("layoutWidget")

        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)

        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)

        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)

        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_3)

        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)

        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)

        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)

        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.spinBox.setValue(1)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox)

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(460, 380, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 380, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(660, 380, 75, 23))
        self.pushButton_3.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)

        ## '''********************'''
        self.pushButton.clicked.connect(self.select_ok)
        self.pushButton.clicked.connect(Dialog.close)

        self.pushButton_2.clicked.connect(Dialog.close)

        #
        # self.pushButton_3.clicked.connect(Dialog.close)


        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        self.checkBox.setText(_translate("Dialog", "返工件"))
        self.checkBox.stateChanged.connect(self.checkLanguage)

        self.label_4.setText(_translate("Dialog", "型号："))
        self.label_5.setText(_translate("Dialog", "F00RJ01613"))
        self.label.setText(_translate("Dialog", "加工机床号"))

        self.comboBox.setItemText(0, _translate("Dialog", "BLM_5"))
        self.comboBox.setItemText(1, _translate("Dialog", "BML_6"))
        self.comboBox.setItemText(2, _translate("Dialog", "BML_7"))
        self.comboBox.setItemText(3, _translate("Dialog", "BLM_8"))
        self.comboBox.setItemText(4, _translate("Dialog", "PW_1"))
        self.comboBox.setItemText(5, _translate("Dialog", "PW_2"))
        self.comboBox.setItemText(6, _translate("Dialog", "Brushing_1"))
        self.comboBox.setItemText(7, _translate("Dialog", "Brushing_2"))

        self.label_2.setText(_translate("Dialog", "目检台号："))
        self.label_3.setText(_translate("Dialog", "VI_4"))
        self.label_6.setText(_translate("Dialog", "不良原因"))

        self.comboBox_2.setItemText(0, _translate("Dialog", "小端面毛刺"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "小端面损伤"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "小端面漏磨"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "定位孔毛刺"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "内孔未完全磨出"))
        self.comboBox_2.currentIndexChanged.connect(self.selectionchange_2)

        self.label_7.setText(_translate("Dialog", "  数  量  "))
        global num
        self.num = 0
        global 是否返工
        self.是否返工 = '报废'

        self.pushButton.setText(_translate("Dialog", "OK"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.num = self.spinBox.value()
        self.spinBox.valueChanged.connect(self.change_table)

        self.pushButton_3.setText(_translate("Dialog", "test"))

    def change_table(self):
        global num;
        self.num = self.spinBox.value()


    def select_ok(self,Dialog):
        # super(Ui_Dialog, self).select_ok(Dialog.close)
        main = QMainWindow()
        main_ui = ui.Ui_MainWindow()
        main_ui.setupUi(main)
        print(self.num)
        if self.num==0:
            pass
        else:
            try:
                df = pd.read_excel(r'C:\Users\LVA2WX\Desktop\ui\test.xlsx')
                last_index = int(df.tail(1).ID)
                value_list=[last_index+1,main_ui.目检台号,main_ui.目检型号,main_ui.机床号,self.comboBox_2.currentText(),self.num,main_ui.text,'正常量产',self.是否返工]
                df2 = pd.DataFrame(value_list).T
                df2.columns = df.columns
                df_new = pd.concat([df, df2], ignore_index=True)
                df_new.to_excel(r'C:\Users\LVA2WX\Desktop\ui\test.xlsx',index=False)
                print(value_list);


            except Exception as e:
                    print(e)




    def selectionchange_2(self,i):
        #currentText()：返回选中选项的文本
        不良原因=self.comboBox_2.currentText()

    def checkLanguage(self, state):
        if state == QtCore.Qt.Unchecked:
            self.是否返工='报废'
        elif state == QtCore.Qt.Checked:
            self.是否返工 = '返工'

