# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(760, 519)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(190, 320, 361, 21))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(529, 146, 56, 17))
        self.checkBox.setObjectName("checkBox")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(530, 170, 28, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(564, 170, 60, 16))
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 140, 165, 93))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox.setText(_translate("Dialog", "返工件"))
        self.label_4.setText(_translate("Dialog", "型号："))
        self.label_5.setText(_translate("Dialog", "F00RJ01613"))
        self.label.setText(_translate("Dialog", "加工机床号"))
        self.comboBox.setItemText(0, _translate("Dialog", "BLM_5"))
        self.comboBox.setItemText(1, _translate("Dialog", "BML_6"))
        self.comboBox.setItemText(2, _translate("Dialog", "BML_7"))
        self.comboBox.setItemText(3, _translate("Dialog", "BLM_8"))
        self.comboBox.setItemText(4, _translate("Dialog", "PW_1"))
        self.comboBox.setItemText(5, _translate("Dialog", "PW_2"))
        self.comboBox.setItemText(6, _translate("Dialog", "Brushing_1"))
        self.comboBox.setItemText(7, _translate("Dialog", "Brushing_2"))
        self.label_2.setText(_translate("Dialog", "目检台号："))
        self.label_3.setText(_translate("Dialog", "VI_4"))
        self.label_6.setText(_translate("Dialog", "不良原因"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "其他"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "小端面毛刺"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "小端面损伤"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "小端面漏磨"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "大端面损伤"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "大端面毛刺"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "大端面漏磨"))
        self.comboBox_2.setItemText(7, _translate("Dialog", "定位孔毛刺"))
        self.comboBox_2.setItemText(8, _translate("Dialog", "内孔未完全磨出"))
        self.comboBox_2.setItemText(9, _translate("Dialog", "空气余隙损伤"))
        self.comboBox_2.setItemText(10, _translate("Dialog", "空气余隙漏磨"))
        self.comboBox_2.setItemText(11, _translate("Dialog", "环面毛刺"))
        self.comboBox_2.setItemText(12, _translate("Dialog", "环面损伤"))
        self.comboBox_2.setItemText(13, _translate("Dialog", "竖槽毛刺"))
        self.comboBox_2.setItemText(14, _translate("Dialog", "边孔毛刺"))
        self.comboBox_2.setItemText(15, _translate("Dialog", "其他毛刺"))
        self.comboBox_2.setItemText(16, _translate("Dialog", "其他磨圆"))
        self.comboBox_2.setItemText(17, _translate("Dialog", "其他漏磨"))
        self.label_7.setText(_translate("Dialog", "数量"))

