{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0d649c4a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#导入库\n",
    "import time\n",
    "from pyecharts.charts import Map,Pie,Radar#地图，饼形图，雷达图\n",
    "from pyecharts import options as opts\n",
    "import json\n",
    "import requests\n",
    "import random\n",
    "import pandas as pd\n",
    "from pyecharts.commons.utils import JsCode\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "e34d4fc5",
   "metadata": {},
   "outputs": [],
   "source": [
    "csv_data = pd.read_csv(r'C:\\Users\\Alex yu\\Desktop\\compare.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a8450d59",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>provinceEnglishName</th>\n",
       "      <th>累计确诊</th>\n",
       "      <th>当前确诊</th>\n",
       "      <th>累计死亡</th>\n",
       "      <th>累计治愈</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>国内</td>\n",
       "      <td>127710</td>\n",
       "      <td>2854</td>\n",
       "      <td>5697</td>\n",
       "      <td>119159</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>国外</td>\n",
       "      <td>260893315</td>\n",
       "      <td>29104581</td>\n",
       "      <td>5188595</td>\n",
       "      <td>226835799</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  provinceEnglishName       累计确诊      当前确诊     累计死亡       累计治愈\n",
       "0                  国内     127710      2854     5697     119159\n",
       "1                  国外  260893315  29104581  5188595  226835799"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "csv_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "fec7d8aa",
   "metadata": {},
   "outputs": [],
   "source": [
    "fn = \"\"\"\n",
    "    function(params) {\n",
    "        if(params.name == '国外')\n",
    "            return '\\\\n\\\\n\\\\n\\\\n\\\\n' + params.name + ' : ' + params.value+'\\\\n\\\\n';\n",
    "        return params.seriesName + '\\\\n' + params.name +' : ' +params.value;\n",
    "    }\n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "def new_label_opts():\n",
    "    return opts.LabelOpts(formatter=JsCode(fn), position=\"center\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "3d09b10c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "<script>\n",
       "    require.config({\n",
       "        paths: {\n",
       "            'echarts':'https://assets.pyecharts.org/assets/echarts.min', 'infographic':'https://assets.pyecharts.org/assets/themes/infographic'\n",
       "        }\n",
       "    });\n",
       "</script>\n",
       "\n",
       "        <div id=\"95bafd54201f4cc288466690a7646789\" style=\"width:1000px; height:500px;\"></div>\n",
       "\n",
       "<script>\n",
       "        require(['echarts', 'infographic'], function(echarts) {\n",
       "                var chart_95bafd54201f4cc288466690a7646789 = echarts.init(\n",
       "                    document.getElementById('95bafd54201f4cc288466690a7646789'), 'infographic', {renderer: 'canvas'});\n",
       "                var option_95bafd54201f4cc288466690a7646789 = {\n",
       "    \"animation\": true,\n",
       "    \"animationThreshold\": 2000,\n",
       "    \"animationDuration\": 1000,\n",
       "    \"animationEasing\": \"cubicOut\",\n",
       "    \"animationDelay\": 0,\n",
       "    \"animationDurationUpdate\": 300,\n",
       "    \"animationEasingUpdate\": \"cubicOut\",\n",
       "    \"animationDelayUpdate\": 0,\n",
       "    \"series\": [\n",
       "        {\n",
       "            \"type\": \"pie\",\n",
       "            \"name\": \"\\u7d2f\\u8ba1\\u786e\\u8bca\",\n",
       "            \"clockwise\": true,\n",
       "            \"data\": [\n",
       "                {\n",
       "                    \"name\": \"\\u56fd\\u5185\",\n",
       "                    \"value\": 127710\n",
       "                },\n",
       "                {\n",
       "                    \"name\": \"\\u56fd\\u5916\",\n",
       "                    \"value\": 260893315\n",
       "                }\n",
       "            ],\n",
       "            \"radius\": [\n",
       "                60,\n",
       "                90\n",
       "            ],\n",
       "            \"center\": [\n",
       "                \"30%\",\n",
       "                \"30%\"\n",
       "            ],\n",
       "            \"label\": {\n",
       "                \"show\": true,\n",
       "                \"position\": \"center\",\n",
       "                \"margin\": 8,\n",
       "                \"formatter\":     function(params) {        if(params.name == '\\u56fd\\u5916')            return '\\n\\n\\n\\n\\n' + params.name + ' : ' + params.value+'\\n\\n';        return params.seriesName + '\\n' + params.name +' : ' +params.value;    }    \n",
       "            },\n",
       "            \"tooltip\": {\n",
       "                \"show\": true,\n",
       "                \"trigger\": \"item\",\n",
       "                \"triggerOn\": \"mousemove|click\",\n",
       "                \"axisPointer\": {\n",
       "                    \"type\": \"line\"\n",
       "                },\n",
       "                \"showContent\": true,\n",
       "                \"alwaysShowContent\": false,\n",
       "                \"showDelay\": 0,\n",
       "                \"hideDelay\": 100,\n",
       "                \"formatter\": \"{a} <br/>{b}: {c} ({d}%)\",\n",
       "                \"textStyle\": {\n",
       "                    \"fontSize\": 14\n",
       "                },\n",
       "                \"borderWidth\": 0,\n",
       "                \"padding\": 5\n",
       "            },\n",
       "            \"rippleEffect\": {\n",
       "                \"show\": true,\n",
       "                \"brushType\": \"stroke\",\n",
       "                \"scale\": 2.5,\n",
       "                \"period\": 4\n",
       "            }\n",
       "        },\n",
       "        {\n",
       "            \"type\": \"pie\",\n",
       "            \"name\": \"\\u5f53\\u524d\\u786e\\u8bca\",\n",
       "            \"clockwise\": true,\n",
       "            \"data\": [\n",
       "                {\n",
       "                    \"name\": \"\\u56fd\\u5185\",\n",
       "                    \"value\": 2854\n",
       "                },\n",
       "                {\n",
       "                    \"name\": \"\\u56fd\\u5916\",\n",
       "                    \"value\": 29104581\n",
       "                }\n",
       "            ],\n",
       "            \"radius\": [\n",
       "                60,\n",
       "                90\n",
       "            ],\n",
       "            \"center\": [\n",
       "                \"70%\",\n",
       "                \"30%\"\n",
       "            ],\n",
       "            \"label\": {\n",
       "                \"show\": true,\n",
       "                \"position\": \"center\",\n",
       "                \"margin\": 8,\n",
       "                \"formatter\":     function(params) {        if(params.name == '\\u56fd\\u5916')            return '\\n\\n\\n\\n\\n' + params.name + ' : ' + params.value+'\\n\\n';        return params.seriesName + '\\n' + params.name +' : ' +params.value;    }    \n",
       "            },\n",
       "            \"tooltip\": {\n",
       "                \"show\": true,\n",
       "                \"trigger\": \"item\",\n",
       "                \"triggerOn\": \"mousemove|click\",\n",
       "                \"axisPointer\": {\n",
       "                    \"type\": \"line\"\n",
       "                },\n",
       "                \"showContent\": true,\n",
       "                \"alwaysShowContent\": false,\n",
       "                \"showDelay\": 0,\n",
       "                \"hideDelay\": 100,\n",
       "                \"formatter\": \"{a} <br/>{b}: {c} ({d}%)\",\n",
       "                \"textStyle\": {\n",
       "                    \"fontSize\": 14\n",
       "                },\n",
       "                \"borderWidth\": 0,\n",
       "                \"padding\": 5\n",
       "            },\n",
       "            \"rippleEffect\": {\n",
       "                \"show\": true,\n",
       "                \"brushType\": \"stroke\",\n",
       "                \"scale\": 2.5,\n",
       "                \"period\": 4\n",
       "            }\n",
       "        },\n",
       "        {\n",
       "            \"type\": \"pie\",\n",
       "            \"name\": \"\\u7d2f\\u8ba1\\u6cbb\\u6108\",\n",
       "            \"clockwise\": true,\n",
       "            \"data\": [\n",
       "                {\n",
       "                    \"name\": \"\\u56fd\\u5185\",\n",
       "                    \"value\": 119159\n",
       "                },\n",
       "                {\n",
       "                    \"name\": \"\\u56fd\\u5916\",\n",
       "                    \"value\": 226835799\n",
       "                }\n",
       "            ],\n",
       "            \"radius\": [\n",
       "                60,\n",
       "                90\n",
       "            ],\n",
       "            \"center\": [\n",
       "                \"30%\",\n",
       "                \"75%\"\n",
       "            ],\n",
       "            \"label\": {\n",
       "                \"show\": true,\n",
       "                \"position\": \"center\",\n",
       "                \"margin\": 8,\n",
       "                \"formatter\":     function(params) {        if(params.name == '\\u56fd\\u5916')            return '\\n\\n\\n\\n\\n' + params.name + ' : ' + params.value+'\\n\\n';        return params.seriesName + '\\n' + params.name +' : ' +params.value;    }    \n",
       "            },\n",
       "            \"tooltip\": {\n",
       "                \"show\": true,\n",
       "                \"trigger\": \"item\",\n",
       "                \"triggerOn\": \"mousemove|click\",\n",
       "                \"axisPointer\": {\n",
       "                    \"type\": \"line\"\n",
       "                },\n",
       "                \"showContent\": true,\n",
       "                \"alwaysShowContent\": false,\n",
       "                \"showDelay\": 0,\n",
       "                \"hideDelay\": 100,\n",
       "                \"formatter\": \"{a} <br/>{b}: {c} ({d}%)\",\n",
       "                \"textStyle\": {\n",
       "                    \"fontSize\": 14\n",
       "                },\n",
       "                \"borderWidth\": 0,\n",
       "                \"padding\": 5\n",
       "            },\n",
       "            \"rippleEffect\": {\n",
       "                \"show\": true,\n",
       "                \"brushType\": \"stroke\",\n",
       "                \"scale\": 2.5,\n",
       "                \"period\": 4\n",
       "            }\n",
       "        },\n",
       "        {\n",
       "            \"type\": \"pie\",\n",
       "            \"name\": \"\\u7d2f\\u8ba1\\u6b7b\\u4ea1\",\n",
       "            \"clockwise\": true,\n",
       "            \"data\": [\n",
       "                {\n",
       "                    \"name\": \"\\u56fd\\u5185\",\n",
       "                    \"value\": 5697\n",
       "                },\n",
       "                {\n",
       "                    \"name\": \"\\u56fd\\u5916\",\n",
       "                    \"value\": 5188595\n",
       "                }\n",
       "            ],\n",
       "            \"radius\": [\n",
       "                60,\n",
       "                90\n",
       "            ],\n",
       "            \"center\": [\n",
       "                \"70%\",\n",
       "                \"75%\"\n",
       "            ],\n",
       "            \"label\": {\n",
       "                \"show\": true,\n",
       "                \"position\": \"center\",\n",
       "                \"margin\": 8,\n",
       "                \"formatter\":     function(params) {        if(params.name == '\\u56fd\\u5916')            return '\\n\\n\\n\\n\\n' + params.name + ' : ' + params.value+'\\n\\n';        return params.seriesName + '\\n' + params.name +' : ' +params.value;    }    \n",
       "            },\n",
       "            \"tooltip\": {\n",
       "                \"show\": true,\n",
       "                \"trigger\": \"item\",\n",
       "                \"triggerOn\": \"mousemove|click\",\n",
       "                \"axisPointer\": {\n",
       "                    \"type\": \"line\"\n",
       "                },\n",
       "                \"showContent\": true,\n",
       "                \"alwaysShowContent\": false,\n",
       "                \"showDelay\": 0,\n",
       "                \"hideDelay\": 100,\n",
       "                \"formatter\": \"{a} <br/>{b}: {c} ({d}%)\",\n",
       "                \"textStyle\": {\n",
       "                    \"fontSize\": 14\n",
       "                },\n",
       "                \"borderWidth\": 0,\n",
       "                \"padding\": 5\n",
       "            },\n",
       "            \"rippleEffect\": {\n",
       "                \"show\": true,\n",
       "                \"brushType\": \"stroke\",\n",
       "                \"scale\": 2.5,\n",
       "                \"period\": 4\n",
       "            }\n",
       "        }\n",
       "    ],\n",
       "    \"legend\": [\n",
       "        {\n",
       "            \"data\": [\n",
       "                \"\\u56fd\\u5185\",\n",
       "                \"\\u56fd\\u5916\"\n",
       "            ],\n",
       "            \"selected\": {},\n",
       "            \"show\": true,\n",
       "            \"padding\": 5,\n",
       "            \"itemGap\": 10,\n",
       "            \"itemWidth\": 25,\n",
       "            \"itemHeight\": 14\n",
       "        }\n",
       "    ],\n",
       "    \"tooltip\": {\n",
       "        \"show\": true,\n",
       "        \"trigger\": \"item\",\n",
       "        \"triggerOn\": \"mousemove|click\",\n",
       "        \"axisPointer\": {\n",
       "            \"type\": \"line\"\n",
       "        },\n",
       "        \"showContent\": true,\n",
       "        \"alwaysShowContent\": false,\n",
       "        \"showDelay\": 0,\n",
       "        \"hideDelay\": 100,\n",
       "        \"textStyle\": {\n",
       "            \"fontSize\": 14\n",
       "        },\n",
       "        \"borderWidth\": 0,\n",
       "        \"padding\": 5\n",
       "    },\n",
       "    \"title\": [\n",
       "        {\n",
       "            \"text\": \"\\u56fd\\u5185\\u5916\\u75ab\\u60c5\\u6570\\u636e\\u5bf9\\u6bd4\",\n",
       "            \"padding\": 5,\n",
       "            \"itemGap\": 10\n",
       "        }\n",
       "    ]\n",
       "};\n",
       "                chart_95bafd54201f4cc288466690a7646789.setOption(option_95bafd54201f4cc288466690a7646789);\n",
       "        });\n",
       "    </script>\n"
      ],
      "text/plain": [
       "<pyecharts.render.display.HTML at 0x2130f081b38>"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pie = (Pie(init_opts=opts.InitOpts(theme='infographic', width='1000px'))\n",
    "       .add(\n",
    "    \"累计确诊\",\n",
    "    [list(i) for i in zip(csv_data['provinceEnglishName'].values.tolist(),csv_data['累计确诊'].values.tolist())],\n",
    "    center=[\"30%\", \"30%\"],\n",
    "    radius=[60, 90],\n",
    "    label_opts=new_label_opts(),\n",
    ")\n",
    "    .add(\n",
    "        \"当前确诊\",\n",
    "        [list(i) for i in zip(csv_data['provinceEnglishName'].values.tolist(),csv_data['当前确诊'].values.tolist())],\n",
    "        center=[\"70%\", \"30%\"],\n",
    "        radius=[60, 90],\n",
    "        label_opts=new_label_opts(),\n",
    ")\n",
    "    .add(\n",
    "        \"累计治愈\",\n",
    "        [list(i) for i in zip(csv_data['provinceEnglishName'].values.tolist(),csv_data['累计治愈'].values.tolist())],\n",
    "        center=[\"30%\", \"75%\"],\n",
    "        radius=[60, 90],\n",
    "        label_opts=new_label_opts(),\n",
    ")\n",
    "    .add(\n",
    "        \"累计死亡\",\n",
    "        [list(i) for i in zip(csv_data['provinceEnglishName'].values.tolist(),csv_data['累计死亡'].values.tolist())],\n",
    "        center=[\"70%\", \"75%\"],\n",
    "        radius=[60, 90],\n",
    "        label_opts=new_label_opts(),\n",
    ")\n",
    "    .set_global_opts(\n",
    "        title_opts=opts.TitleOpts(title=\"国内外疫情数据对比\"),\n",
    "        legend_opts=opts.LegendOpts(is_show=True),)\n",
    "    .set_series_opts(\n",
    "        tooltip_opts=opts.TooltipOpts(\n",
    "            trigger=\"item\", formatter=\"{a} <br/>{b}: {c} ({d}%)\"\n",
    "        ),)\n",
    ")\n",
    "\n",
    "pie.render_notebook()\n",
    "# pie.render(\"国内外疫情对比.html\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8b49b5a9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
